services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: afrisat-db
    restart: always
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=4"
      - "-c"
      - "max_replication_slots=4"
    ports:
      - "5434:5432"

  afrisat-be:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=afrisat-db
      - DB_PORT=5432
      - DB_NAME=local
      - DB_SCHEMA=users
      - JWT_SECRET_KEY=n3Isk0a9rvmBMOzwQfEv58/hKwam1//8eKmVvjRPZWY=
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
